
CREATE TABLE MENU_TABLE(
	SEQ NUMBER(8) PRIMARY KEY,
	MENU VARCHAR(40) NOT NULL,
	SHORT_PRICE NUMBER(8) NOT NULL,
	TALL_PRICE NUMBER(8) NOT NULL,
	GRANDE_PRICE NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_MENU
START WITH 1
INCREMENT BY 1;

DROP TABLE MENU_TABLE;

select * from MENU_TABLE;
