DROP TABLE BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ORDER;

CREATE TABLE ORDER_TABLE(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(30) NOT NULL,
	MENU VARCHAR2(200) NOT NULL,
	SYRUP VARCHAR2(200),
	CUP_SIZE VARCHAR2(200) NOT NULL,
	SHOT VARCHAR2(200),
	WHEEPING VARCHAR2(200),
	CUP NUMBER(8) NOT NULL,
	PRICE NUMBER(8) NOT NULL,
	WDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_ORDER
START WITH 1
INCREMENT BY 1;

select * from order_table;

ALTER TABLE ORDER_TABLE
ADD CONSTRAINT FK_ORDER_TABLE_ID FOREIGN KEY(ID)
REFERENCES ORDER_MEMBER(ID);

 INSERT INTO ORDER_TABLE(SEQ, ID, MENU, SYRUP, CUP_SIZE, SHOT, WHEEPING,
 CUP, PRICE, WDATE) 
   VALUES(SEQ_ORDER.NEXTVAL, '1', '1', '1', '1', '1', '1', 1, 1, SYSDATE)
